### ISSUE TITLE
Allow (easier) overriding max level of all enchantments

### ISSUE THREAD

**Issue by KadTheHunter** [Brokkonaut/Bukkit-CreativeItemControl#10]
Title sums it up. Any item with an enchantment level greater than 1 will have its enchantments removed, if the enchantment is not normally allowed on the item, or is above the level normally allowed on the item.

In the config, all options under the relative components are set to true:
```
      enchantable:
        allow: true
      enchantment_glint_override:
        allow: true
      enchantments:
        allow_on_all_items: true
        allow_hidden: true
        override_max_level: {256}
```

I even tried overriding the max level (with 255 and then with 256), but it made no difference.

This issue can be replicated with the following steps:
- Apply Protection IV to an Oak Plank, Protection IV to any Helmet, and Protection V to any helmet
- Add all the items into a shulker
- Place and open the shulker
- Notice how the Oak Planks and Prot V helmet are wiped of their enchants, both in the shulker you placed and the one in your inventory

This was replicated and proven on a PaperMC server with only CreativeItemControl installed.

Relevant versions:
Minecraft 1.21.4
Paper 1.21.4-228-ver/1.21.4@c2bb144 (2025-05-07T23:25:36Z) (Implementing API version 1.21.4-R0.1-SNAPSHOT)
CreativeItemControl v1-20-SNAPSHOT-110
